version: '3.1'
volumes:
  pgdata:
  static_files:
  media_content:
services:
  postgre_db:
    image: library/postgres:latest
    environment:
      POSTGRES_DB: zhehe-db
      POSTGRES_USER: jonas
      POSTGRES_PASSWORD: password
    volumes:
      - pgdata:/var/utils/posgresql/data
    ports:
      - 5432:5432
  zhehe:
      # image: library/python:3.8-buster
      build:
        context: .
        dockerfile: docker/zhehe/Dockerfile
      restart: always
      volumes:
      - ./zhehe:/zhehe
      - static_files:/static_files
      - media_content:/media_content
      ports:
      - 8000:8000
      command: gunicorn -w 4 zhehe.wsgi -b 0.0.0.0:8000
  nginx:
      # image: library/nginx:latest
      build:
        context: .
        dockerfile: docker/nginx/Dockerfile
      volumes:
        - static_files:/static_files
        - media_content:/media_content
      ports:
        - 8080:80
