# Generated by Django 3.0.8 on 2020-07-19 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zhehe_user_app', '0003_document_document_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact_info',
            name='concern',
            field=models.CharField(default='now', max_length=100),
            preserve_default=False,
        ),
    ]
