# Generated by Django 3.0.8 on 2020-07-20 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zhehe_user_app', '0004_contact_info_concern'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='document',
            name='id',
        ),
        migrations.AlterField(
            model_name='document',
            name='document_path',
            field=models.FilePathField(default='abs', primary_key=True, serialize=False),
            preserve_default=False,
        ),
    ]
