# Generated by Django 3.0.8 on 2020-07-20 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zhehe_user_app', '0005_auto_20200720_2129'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='documentpage',
            name='id',
        ),
        migrations.AlterField(
            model_name='document',
            name='document_path',
            field=models.CharField(max_length=500, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='documentpage',
            name='doc_page_path',
            field=models.CharField(max_length=500, primary_key=True, serialize=False),
        ),
    ]
